name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        service_account: 'vriksh-jarvis@prag-2019.iam.gserviceaccount.com'

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy vriksh-jarvis-v1 \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point chat_with_gpt \
          --project prag-2019
